---
- name: create /var/www
  file: path=/var/www state=directory

- name: create site symlink
  file: src=/vagrant dest=/var/www/site state=link
  notify: restart apache

- name: ensure apache is installed
  apt: name=apache2 state=present
  tags: lamp

- name: make sure apache is running
  action: service name=apache2 state=started enabled=true
  tags: lamp

- file: src=/etc/apache2/mods-available/rewrite.load dest=/etc/apache2/mods-enabled/rewrite.load state=link
  notify: restart apache
  tags: lamp

- file: src=/etc/apache2/mods-available/headers.load dest=/etc/apache2/mods-enabled/headers.load state=link
  notify: restart apache
  tags: lamp

- copy: src=/vagrant/ansible/templates/site.conf dest=/etc/apache2/sites-enabled/site.conf
  notify: restart apache
  tags: lamp

- file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify: restart apache
  tags: lamp

- file: path=/etc/apache2/conf.d state=directory
  tags: lamp

- copy: src=/vagrant/ansible/templates/fqdn.conf dest=/etc/apache2/conf.d/fqdn.conf
  notify: restart apache
  tags: lamp

- copy: src=/vagrant/ansible/templates/nosendfile.conf dest=/etc/apache2/conf.d/nosendfile.conf
  notify: restart apache
  tags: lamp
